---
name: Test
on:  # yamllint disable-line rule:truthy
  push:

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v5
      - name: Test
        uses: robherley/go-test-action@v1
        with:
          cover: true
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
