---
name: Test
on:  # yamllint disable-line rule:truthy
  push:

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v5
      - name: Generate Test Data
        run: |
          ./tools/build-plugins.sh -t \
            -i ./examples/ \
            -o ./plugins/
          ./tools/build-plugins.sh -t \
            -i ./testdata/bundle/bad_plugins/ \
            -o ./testdata/bundle/generated/
      - name: Test
        run: |
          go test ./... \
            -covermode=set -coverpkg=./... -coverprofile=coverage.txt
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
